set_property SRC_FILE_INFO {cfile:C:/DEV/sysnum/projet-sysnum-multiplicateur-de-matrice-ll/nano2019v01e_vide/artix7/artix7.srcs/constrs_1/new/nanoControleur.xdc rfile:../../../artix7.srcs/constrs_1/new/nanoControleur.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K19   [get_ports clk_i]; set_property IOSTANDARD LVCMOS33 [get_ports clk_i];  set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {clk_i}]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G20   [get_ports port_a_i[0]]; set_property IOSTANDARD LVCMOS33 [get_ports port_a_i[0]]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H22   [get_ports port_a_i[1]]; set_property IOSTANDARD LVCMOS33 [get_ports port_a_i[1]]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J21   [get_ports port_a_i[2]]; set_property IOSTANDARD LVCMOS33 [get_ports port_a_i[2]]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J22   [get_ports port_a_i[3]]; set_property IOSTANDARD LVCMOS33 [get_ports port_a_i[3]]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K21   [get_ports port_a_i[4]]; set_property IOSTANDARD LVCMOS33 [get_ports port_a_i[4]]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K22   [get_ports port_a_i[5]]; set_property IOSTANDARD LVCMOS33 [get_ports port_a_i[5]]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M21   [get_ports port_a_i[6]]; set_property IOSTANDARD LVCMOS33 [get_ports port_a_i[6]]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M22   [get_ports port_a_i[7]]; set_property IOSTANDARD LVCMOS33 [get_ports port_a_i[7]]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N22   [get_ports port_b_i[0]]; set_property IOSTANDARD LVCMOS33 [get_ports port_b_i[0]]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G17   [get_ports port_b_i[1]]; set_property IOSTANDARD LVCMOS33 [get_ports port_b_i[1]]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G18   [get_ports port_b_i[2]]; set_property IOSTANDARD LVCMOS33 [get_ports port_b_i[2]]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H18   [get_ports port_b_i[3]]; set_property IOSTANDARD LVCMOS33 [get_ports port_b_i[3]]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H20   [get_ports port_b_i[4]]; set_property IOSTANDARD LVCMOS33 [get_ports port_b_i[4]]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J17   [get_ports port_b_i[5]]; set_property IOSTANDARD LVCMOS33 [get_ports port_b_i[5]]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J20   [get_ports port_b_i[6]]; set_property IOSTANDARD LVCMOS33 [get_ports port_b_i[6]]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H15   [get_ports port_b_i[7]]; set_property IOSTANDARD LVCMOS33 [get_ports port_b_i[7]]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G13   [get_ports port_a_o[0]]; set_property IOSTANDARD LVCMOS33 [get_ports port_a_o[0]]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H14   [get_ports port_a_o[1]]; set_property IOSTANDARD LVCMOS33 [get_ports port_a_o[1]]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G15   [get_ports port_a_o[2]]; set_property IOSTANDARD LVCMOS33 [get_ports port_a_o[2]]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G16   [get_ports port_a_o[3]]; set_property IOSTANDARD LVCMOS33 [get_ports port_a_o[3]]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H17   [get_ports port_a_o[4]]; set_property IOSTANDARD LVCMOS33 [get_ports port_a_o[4]]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J16   [get_ports port_a_o[5]]; set_property IOSTANDARD LVCMOS33 [get_ports port_a_o[5]]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K17   [get_ports port_a_o[6]]; set_property IOSTANDARD LVCMOS33 [get_ports port_a_o[6]]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L20   [get_ports port_a_o[7]]; set_property IOSTANDARD LVCMOS33 [get_ports port_a_o[7]]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L18   [get_ports port_b_o[0]]; set_property IOSTANDARD LVCMOS33 [get_ports port_b_o[0]]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L16   [get_ports port_b_o[1]]; set_property IOSTANDARD LVCMOS33 [get_ports port_b_o[1]]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L15   [get_ports port_b_o[2]]; set_property IOSTANDARD LVCMOS33 [get_ports port_b_o[2]]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M20   [get_ports port_b_o[3]]; set_property IOSTANDARD LVCMOS33 [get_ports port_b_o[3]]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N19   [get_ports port_b_o[4]]; set_property IOSTANDARD LVCMOS33 [get_ports port_b_o[4]]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N20   [get_ports port_b_o[5]]; set_property IOSTANDARD LVCMOS33 [get_ports port_b_o[5]]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J15   [get_ports port_b_o[6]]; set_property IOSTANDARD LVCMOS33 [get_ports port_b_o[6]]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K16   [get_ports port_b_o[7]]; set_property IOSTANDARD LVCMOS33 [get_ports port_b_o[7]]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T18   [get_ports reset_n_i];   set_property IOSTANDARD LVCMOS33 [get_ports reset_n_i]
